name: sip_calculator
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.61.0
  lottie: ^2.3.2
  flutter_launcher_icons: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/finance_calculator_icon3.png"